### ISSUE TITLE
Why git token is needed? 

### ISSUE THREAD

**Issue by Eximinati** [TheTeamAlexa/Alexa-Hosting#1]
Why is it necessary to give git token?

**Comment by TheTeamAlexa** [comment]
**Before I start we I wanna tell you something** 

1. Remember that we have to do all the process on second account not on main account due to account security and protection
2. As I told in my video our repo should be private so to access the private repo we need git token 
3. No need to take any tension about revealing of git token except owner no one can see your secrets like git name, git token etc
4. Our bot will deploy on github workflow so to commit loop time also we need token to access our repo 
**That's the reason we need git token in our secrets thanks for making question**

**Comment by TheTeamAlexa** [comment]
It's done
